FROM golang:1.24-alpine3.22 AS base
#
# To accelerate the build process, you may uncomment this section.
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
#
RUN apk add --no-cache make clang15 libbpf-dev curl git \
    musl-dev capnproto-dev # for golangci-lint, capnp compile

ENV GOPATH="/go"
ENV GOROOT="/usr/local/go"
ENV GOPROXY="https://goproxy.cn,https://goproxy.io,direct"
ENV PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/lib/llvm15/bin:${PATH}"

# For golang 1.23.0
# gofumpt@v0.8.0, https://github.com/mvdan/gofumpt/blob/master/CHANGELOG.md
# goimports@v0.36.0
# golangci-lint https://github.com/golangci/golangci-lint/blob/main/CHANGELOG-v1.md
RUN go install mvdan.cc/gofumpt@v0.8.0 && \
    go install golang.org/x/tools/cmd/goimports@v0.36.0 && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2 && \
    go install github.com/vektra/mockery/v2@v2.53.6 && \
    go install capnproto.org/go/capnp/v3/capnpc-go@v3.1.0-alpha.2
