# log-level: Debug, Info, Warn, Error, Panic
LogLevel = "Info"

[RuntimeCgroup]
# CfsInitQuota, CfsRuntimeQuota: run-time replenishegitd
# within a period (in microseconds)
  # LimitCPU: cpu limit in cores
  LimitCPU = 20
  # LimitMem: memory limit in MB
  LimitMem = 4096

[APIServer]
  # TCPAddr is the tcp monitoring information of the HUATUO server
  TCPAddr = ":12740"

[TaskConfig]
  # MaxProfilingTasksPerHost is the maximum number of profiling tasks allowed per host
  MaxProfilingTasksPerHost = 3
  # MaxTracingTasksPerHost is the maximum number of tracing tasks allowed per host
  MaxTracingTasksPerHost = 5
  # MaxTotalProfilingTasks is the maximum number of total profiling tasks allowed
  MaxTotalProfilingTasks = 500
  # MaxTotalTracingTasks is the maximum number of total tracing tasks allowed
  MaxTotalTracingTasks = 1000

[ElasticSearch]
  Debug = false
  Address = ""
  Username = ""
  Password = ""
  Index = ""

[Auth]
  # User authentication configurations
  [[Auth.users]]
    ID = "a800ed4b075ecacd2dfc246a9a1ae87a"
    Name = "Administrator"
    IsAdmin = true

  [[Auth.users]]
    ID = "2649c74e8baac5a727ea862756c8299b"
    Name = "huatuo-front"
    Permissions = ["/v1/traces/**", "/v1/traces", "/v1/profiles", "/v1/profiles/**"]
    IsAdmin = false

[Profiling]
  # CPUProfilingInterval is the interval for CPU profiling
  CPUProfilingInterval = 10
  # MemoryProfilingInterval is the interval for Memory profiling
  MemoryProfilingInterval = 10
  # CPUSingleTraceTimeout is the timeout for CPU single trace
  CPUSingleTraceTimeout = 20
  # MemorySingleTraceTimeout is the timeout for Memory single trace
  MemorySingleTraceTimeout = 20
  # ThirdPartyToolLimit is the limit for third party tool
  ThirdPartyToolLimit = 10
